server:
  port: 8085
  servlet:
    context-path: /api

hapi:
  fhir:
    url: ${HAPI_FHIR_URL:http://localhost:8080/fhir}

fhir-base-url: ${FHIR_BASE_URL:http://ecqi.healthit.gov/ecqms}

madie:
  cql-elm:
    service:
      base-url: ${ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api}
      human-readable-uri: /human-readable
#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_PATH:/swagger}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}