server:
  port: 8085
  servlet:
    context-path: /api

madie:
  cql-elm:
    service:
      base-url: ${FHIR_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8083/api/fhir}
      effective-data-requirements-uri: /effective-data-requirements
  library:
    service:
      baseUrl: ${CQL_LIBRARY_SERVICE_URL:http://localhost:8082/api}
      versioned:
        uri: /cql-libraries/versioned
  url: ${MADIE_URL:https://madie.cms.gov}
  resource:
    url: https://madie.cms.gov
  useMultipleStratAssociation: ${USE_MULTIPLE_STRAT_ASSOCIATION:true}

#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_PATH:/swagger}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

caching:
  spring:
    libraries:
      ttlMillis: 3600000
