server:
  port: 8085
  servlet:
    context-path: /api

hapi:
  fhir:
    url: ${HAPI_FHIR_URL:http://localhost:8080/fhir}

fhir-base-url: ${FHIR_BASE_URL:http://ecqi.healthit.gov/ecqms}

default-mp-start-date: 01/01/2023
default-mp-end-date: 31/12/2023

#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_PATH:/swagger}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}