server:
  port: 8085
  servlet:
    context-path: /api

validation:
  terminology:
    validateDisplay: false

madie:
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8088/api}
  cql-elm:
    service:
      base-url: ${FHIR_ELM_TRANSLATOR_SERVICE_URL:http://localhost:8083/api/fhir}
      effective-data-requirements-uri: /effective-data-requirements
  library:
    service:
      baseUrl: ${CQL_LIBRARY_SERVICE_URL:http://localhost:8082/api}
      versioned:
        uri: /cql-libraries/versioned
  url: ${MADIE_URL:https://madie.cms.gov}
  resource:
    url: https://madie.cms.gov
  terminology:
    service:
      base-url: ${TERMINOLOGY_SERVICE_URL:http://localhost:8081/api/terminology}
      validate-codes: /validations/codes
      api-key: ${TERMINOLOGY_API_KEY:0a51991c}
  service-config:
    json-url: ${SERVICE_CONFIG_JSON_URL:http://localhost:9000/env-config/serviceConfig.json}

vsac:
  terminology-server-url: https://cts.nlm.nih.gov/fhir
  api-key: ${VSAC_API_KEY:defaultvaluetopreventillegalappstate}

#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_PATH:/swagger}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-madie.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

management:
  endpoints:
    web:
      exposure:
        include: health,caches,metrics,info,cache-inspection
  endpoint:
    health:
      show-details: when-authorized
