server:
  port: 8085
  servlet:
    context-path: /api

hapi:
  fhir:
    url: ${HAPI_FHIR_URL:http://localhost:8080/fhir}

fhir-base-url: ${FHIR_BASEP_URL:http://ecqi.healthit.gov/ecqms}

#springdoc:
#  swagger-ui:
#    path: ${SWAGGER_PATH:/swagger}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-53861726.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}